### ISSUE TITLE
Error in logging from JTDX 1.59

### ISSUE THREAD

**Issue by stephenhouser** [stephenhouser/node-red-contrib-wsjt-x#4]
I found an error throwing with JTDX 1.59 when logging:
 
RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint32 (<anonymous>)
    at Parser.eval [as compiled] (eval at Parser.compile (c:\Users\Peter\.node-red\node_modules\binary-parser-encoder\dist\binary_parser.js:554:25), <anonymous>:339:38)
    at Parser.parse (c:\Users\Peter\.node-red\node_modules\binary-parser-encoder\dist\binary_parser.js:615:21)
    at Object.decode (c:\Users\Peter\.node-red\node_modules\node-red-contrib-wsjt-x\wsjt-x-parser.js:443:31)
    at WSJTXDecodeNode._inputCallback (c:\Users\Peter\.node-red\node_modules\node-red-contrib-wsjt-x\wsjt-x-decode.js:22:26)
    at c:\Users\Peter\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\Node.js:210:26
    at Object.trigger (c:\Users\Peter\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\util\lib\hooks.js:166:13)
    at Node._emitInput (c:\Users\Peter\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\Node.js:202:11)
    at Node.emit (c:\Users\Peter\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\Node.js:186:25)
    at Node.receive (c:\Users\Peter\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\Node.js:485:10)
{ magic: 2914831322, version: 2, type: 5, id: 'JTDX' }
 
The output of the last three lines of your node is:
 
{"magic":2914831322,"schema":2,"type":"logged-adif","id":"JTDX","adif_text":"<adif_ver:5>3.1.0\n<programid:4>JTDX\n<EOH>\n<BAND:3>15m <STATION_CALLSIGN:5>DF6QN <MY_GRIDSQUARE:6>JO41ir <CALL:6>YO3GNF <FREQ:9>21.142659 <MODE:4>MFSK <SUBMODE:3>FT4 <QSO_DATE:8>20221213 <TIME_ON:6>115200 <QSO_DATE_OFF:8>20221213 <TIME_OFF:6>115229 <RST_SENT:3>+14 <RST_RCVD:3>+13 <GRIDSQUARE:4>KN34 <COMMENT:17>Distance: 1574 km <EOR>","freqency":null}
{"magic":2914831322,"schema":2,"type":"heartbeat","id":"JTDX","max_schema_number":3,"version":"2.2.159","freqency":null}
{"magic":2914831322,"schema":2,"type":"status","id":"JTDX","freqency":21140055,"mode":"FT4","dx_call":"YO3GNF","report":14,"tx_mode":"FT4","tx_enabled":true,"transmitting":false,"decoding":false,"rx_df":2349,"tx_df":2604,"de_call":"DF6QN","de_grid":"JO41ir","dx_grid":"KN34","tx_watchdog":false,"sub_mode":"","fast_mode":false,"tx_first":false}
 
The error comes with the first line logged-adif
 
The input payload:
 
[173,188,203,218,0,0,0,2,0,0,0,12,0,0,0,4,74,84,68,88,0,0,1,79,10,60,97,100,105,102,95,118,101,114,58,53,62,51,46,49,46,48,10,60,112,114,111,103,114,97,109,105,100,58,52,62,74,84,68,88,10,60,69,79,72,62,10,60,66,65,78,68,58,51,62,49,53,109,32,60,83,84,65,84,73,79,78,95,67,65,76,76,83,73,71,78,58,53,62,68,70,54,81,78,32,60,77,89,95,71,82,73,68,83,81,85,65,82,69,58,54,62,74,79,52,49,105,114,32,60,67,65,76,76,58,54,62,89,79,51,71,78,70,32,60,70,82,69,81,58,57,62,50,49,46,49,52,50,54,53,57,32,60,77,79,68,69,58,52,62,77,70,83,75,32,60,83,85,66,77,79,68,69,58,51,62,70,84,52,32,60,81,83,79,95,68,65,84,69,58,56,62,50,48,50,50,49,50,49,51,32,60,84,73,77,69,95,79,78,58,54,62,49,49,53,50,48,48,32,60,81,83,79,95,68,65,84,69,95,79,70,70,58,56,62,50,48,50,50,49,50,49,51,32,60,84,73,77,69,95,79,70,70,58,54,62,49,49,53,50,50,57,32,60,82,83,84,95,83,69,78,84,58,51,62,43,49,52,32,60,82,83,84,95,82,67,86,68,58,51,62,43,49,51,32,60,71,82,73,68,83,81,85,65,82,69,58,52,62,75,78,51,52,32,60,67,79,77,77,69,78,84,58,49,55,62,68,105,115,116,97,110,99,101,58,32,49,53,55,52,32,107,109,32,60,69,79,82,62]
 
The same input payload:
 
<image001.jpg>
 
I think your code is looking for frequency but getting null for this …..
Thanks for reading and best regards

**Comment by mcangeli** [comment]
Agreed. It works with WSJT-X and the DX_grid field, if I try to grab the same information from JTDX I get the error above. 
Not a show stopper. 

:)

Otherwise this is great!

**Comment by mcangeli** [comment]
I think that the buffer being used is too small for the data that jtdx is passing (does that make sense?)

**Comment by stephenhouser** [comment]
It does in a way... JTDX forked from WSJT-X and they added some of their own fields that now conflict with newer WSJT-X fields. (from memory) There's not a super-simple way to discern if the data is from JTDX or WSJT-X given the decoding code does not maintain any internal state. That is every packet of data is decoded independently. Any signaling that the data is coming from JTDX would not be kept for later decoding.

My somewhat recent changes might help along the path, but I'll likely need to introduce a setting to say, "parse this as JTDX and not WSJT-X". Which would of course then possibly break something else.

Frankly, I just have not thought about it for a bit and I don't use JTDX so it's not been high on my to-do list.

**Comment by mcangeli** [comment]
> Frankly, I just have not thought about it for a bit and I don't use JTDX so it's not been high on my to-do list.

No worries! I use both (jtdx seems to give better decoding) and this is something I'm just playing with for my own edification. The ability to use this to update the DX path on hamclock is something cool but not "necessary"

**Comment by mariano80** [comment]
Hi! I'm working on a backend that listen the WSJT and JTDX UDP packet. Your code helps me to undestand and decode the data. I have the same problem in JTDX receiving the same error. I'm workin on a fix ecause I use more JTDX than the other.

If any news I'll write you!
Thanks,
Mariano 
LW2DHT

**Comment by mariano80** [comment]
I found a WorkAround that is OK.

class JTDXParser extends WSJTXParser  <-- this is a should corrected in the code.

My WA is

```
const DEFAULT_VERSION = 1.0;

function getParser(version_string, schema) {
	if (typeof (version) != 'number') {
		version = parseFloat(version_string);
	}

	if (version >= 2.6) {
		return new WSJTXParser_v260(schema);
	}

	if (version >= 2.3) {
		return new WSJTXParser_v230(schema);
	}

	if (version >= 2.1) {
		return new WSJTXParser_v210(schema);
	}

	if (version >= 2.0) {
		return new WSJTXParser_v200(schema);
	}
	// Si la version es 1.0 uso el schema de JTDX

	if (version >= 1) {
		return new JTDXParser(schema);
	}
	return new WSJTXParser(schema);
}
```

I'm testing ubt it is working ok. There some diffs between the two soft messages via UDP.

I hope this WA helps you
LW2DHt

**Comment by mcangeli** [comment]
So...

`
// For JTDX (untested)
class JTDXParser extends WSJTXParser_v210 {
	statusParser = this.statusParser
		.uint8('tx_first', { formatter: boolFormatter })
		;
	
	// TODO: v2.1 statsEncoder (JTDX)
}
`

Becomes:
`
// For JTDX (untested)
class JTDXParser extends WSJTXParser_v210 {
	statusParser = this.statusParser
		.uint8('tx_first', { formatter: boolFormatter })
		;
	const DEFAULT_VERSION = 1.0;

	function getParser(version_string, schema) {
		if (typeof (version) != 'number') {
			version = parseFloat(version_string);
		}

		if (version >= 2.6) {
			return new WSJTXParser_v260(schema);
		}

		if (version >= 2.3) {
			return new WSJTXParser_v230(schema);
		}

		if (version >= 2.1) {
			return new WSJTXParser_v210(schema);
		}

		if (version >= 2.0) {
			return new WSJTXParser_v200(schema);
		}
	// Si la version es 1.0 uso el schema de JTDX

		if (version >= 1) {
			return new JTDXParser(schema);
		}
			return new WSJTXParser(schema);
	}
	// TODO: v2.1 statsEncoder (JTDX)
}
`

??
